### ISSUE TITLE
List RCA Action Items

### ISSUE THREAD

**Issue by prafulkoppalkar** [juspay/hyperswitch-web#124]

**Comment by ArushKapoorJuspay** [comment]
- [ ] Publishable key not present should throw an exception in the SDK. P2 #4043
- [ ] Sentry alerts for exceptions. P1 #4044
- [ ] Add count no. of fallback events in analytics - P2 #4046
