### ISSUE TITLE
Monorepo for client core + hyperswitch web

### ISSUE THREAD

**Issue by seekshiva** [juspay/hyperswitch-web#509]
### open for discussion

- list of things to do after repo merge
  - [ ] version bump only happens if web / common changes - github action
  - [ ] trigger release only if web / common changes - github action?

### task list for migration

- [ ] move all content of `hyperswitch-client-core` into `/packages/hyperswitch-client-core` folder
- [ ] move entire hyperswitch-web repo into `packages/hyperswitch-web` folder of hyperswitch-client-core repo
- [ ] update hyperswitch-client-core github actions to only get triggered if client-core / common has a change
- [ ] update hyperswitch-web github actions to only get triggered if hyperswitch-web / common has a change
- [ ] Add Types support for TS merchants and return types - HS - Web
